import os
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_community.tools.wikipedia.tool import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper
from langchain.tools import Tool

def build_research_agent():
    """Initializes the Gemini LLM, Tools, and Agent."""
    
    # 1. Initialize the Gemini LLM
    # We use gemini-1.5-flash because it is fast and supports tool calling beautifully.
    llm = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",
        temperature=0.2
    )

    # 2. Initialize Tools
    search = DuckDuckGoSearchRun()
    wiki = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper(top_k_results=2, doc_content_chars_max=2000))

    tools = [
        Tool(
            name="Web_Search",
            func=search.run,
            description="Useful for searching the web for recent information, news, and current events."
        ),
        Tool(
            name="Wikipedia",
            func=wiki.run,
            description="Useful for finding foundational knowledge, historical facts, and broad overviews of topics."
        )
    ]

    # 3. Create the Prompt Template enforcing the Output Format
    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are an expert Autonomous Research Agent. Your job is to research a given topic using the provided tools and generate a highly structured, professional report.
        
        You MUST structure your final response exactly according to the following format:
        
        [Cover Page]
        Title: [A catchy and appropriate title for the report]
        Topic: [The user's topic]
        Generated by: Autonomous Research Agent
        
        [Introduction]
        (Write a comprehensive introduction based on your research)
        
        [Key Findings]
        (Use bullet points to list the most critical insights, data points, or facts you discovered)
        
        [Challenges]
        (Discuss the obstacles, ethical concerns, or technical difficulties related to the topic)
        
        [Future Scope]
        (Analyze where this topic/technology is heading in the next 5-10 years)
        
        [Conclusion]
        (Provide a strong summarizing conclusion)
        """),
        ("human", "Please research the following topic and generate the report: {input}"),
        ("placeholder", "{agent_scratchpad}"),
    ])

    # 4. Construct the Agent
    agent = create_tool_calling_agent(llm, tools, prompt)
    
    # 5. Create the Agent Executor
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
    
    return agent_executor

def generate_report(topic: str, output_filename: str):
    """Runs the agent on a topic and saves the output to a file."""
    print(f"\n🚀 Starting research on: '{topic}'...\n")
    
    agent = build_research_agent()
    
    try:
        # Run the agent
        result = agent.invoke({"input": topic})
        report_content = result['output']
        
        # Save to file
        with open(output_filename, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        print(f"\n Report successfully generated and saved to {output_filename}")
        
    except Exception as e:
        print(f"\n An error occurred: {e}")

if __name__ == "__main__":
    # Ensure Google API key is set
    if not os.environ.get("GOOGLE_API_KEY"):
        print("Error: GOOGLE_API_KEY environment variable is missing.")
        exit(1)

    # --- Generate Sample Output 1 ---
    topic_1 = "Impact of AI in Healthcare"
    generate_report(topic_1, "Output_1.txt")

    # --- Generate Sample Output 2 ---
    topic_2 = "The Future of Solid State Batteries in Electric Vehicles"
    generate_report(topic_2, "Output_2.txt")